//@ sourceMappingURL=onload.map
// Generated by CoffeeScript 1.6.1
(function() {

  $(function() {
    var arc, change, color, dataset, height, path, pie, radius, svg, width;
    dataset = {
      apples: [53245, 28479],
      oranges: [200, 200]
    };
    width = 1109;
    height = 910;
    radius = 100;
    color = d3.scale.category20();
    pie = d3.layout.pie().sort(null);
    arc = d3.svg.arc().innerRadius(radius - 40).outerRadius(radius - 20);
    svg = d3.select("body").append("svg").attr("width", width).attr("height", height).append("g").attr("transform", "translate(" + width / 2 + "," + height / 2 + ")");
    path = svg.selectAll("path").data(pie(dataset.apples)).enter().append("path").attr("fill", function(d, i) {
      return color(i);
    }).attr("d", arc);
    change = function() {
      console.log([parseInt($('#one').val(), 10) || 1, parseInt($('#two').val(), 10) || 1]);
      path = path.data(pie([parseInt($('#one').val(), 10) || 1, parseInt($('#two').val(), 10) || 1]));
      return path.attr("d", arc);
    };
    return $('#one, #two').on("change", change).change();
  });

}).call(this);
